add_newline = false

format = """
$username$hostname\
$directory\
$git_branch$git_state$git_status\
$c$cmake$lua$java$python$nodejs\
$cmd_duration\
$line_break\
$character"""

[username]
show_always = true
style_user = "bright-black"
style_root = "red"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bright-black"
format = "[@$hostname]($style) "

[directory]
style = "bright-blue"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style) "
style = "purple"

[git_status]
format = "[($conflicted$untracked$modified$staged$renamed$deleted$stashed$ahead_behind)]($style)"
style = "bold purple"
conflicted = "✖"
untracked  = "?"
modified   = "!"
staged     = "+"
renamed    = "→"
deleted    = "✗"
stashed    = "≡"
ahead = "↑"
behind = "↓"
diverged = "↕"

[git_state]
format = "([$state( $progress_current/$progress_total)]($style)) "
style = "purple"

[c]
format = "[$name $version]($style) "
style = "cyan"

[cmake]
format = "[$symbol$version]($style) "
symbol = "CMake "
style = "cyan"

[lua]
format = "[$symbol$version]($style) "
symbol = "Lua "
style = "cyan"

[java]
format = "[$symbol$version]($style) "
symbol = "Java "
style = "cyan"

[python]
format = "[$virtualenv]($style) "
style = "cyan"
detect_extensions = []
detect_files = []

[nodejs]
format = "[$symbol$version]($style) "
symbol = "Node "
style = "cyan"

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"
