add_newline = false

format = """
$username$hostname\
$directory\
$git_branch$git_state$git_status\
$c$cmake$lua$java$python$nodejs\
$cmd_duration\
$line_break\
$character"""

[username]
show_always = true
style_user = "#888ca6"
style_root = "#d20f39"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "#888ca6"
format = "[@$hostname]($style) "

[directory]
style = "#1e66f5"

[character]
success_symbol = "[❯](#40a02b)"
error_symbol = "[❯](#d20f39)"
vimcmd_symbol = "[❮](#40a02b)"

[git_branch]
format = "[$branch]($style) "
style = "#8839ef"

[git_status]
format = "[($conflicted$untracked$modified$staged$renamed$deleted$stashed$ahead_behind)]($style)"
style = "#8839ef"
conflicted = "✖"
untracked  = "?"
modified   = "!"
staged     = "+"
renamed    = "→"
deleted    = "✗"
stashed    = "≡"
ahead = "↑"
behind = "↓"
diverged = "↕"

[git_state]
format = "([$state( $progress_current/$progress_total)]($style)) "
style = "#8839ef"

[c]
format = "[$name $version]($style) "
style = "#179299"

[cmake]
format = "[$symbol$version]($style) "
symbol = "CMake "
style = "#179299"

[lua]
format = "[$symbol$version]($style) "
symbol = "Lua "
style = "#179299"

[java]
format = "[$symbol$version]($style) "
symbol = "Java "
style = "#179299"

[python]
format = "[$virtualenv]($style) "
style = "#179299"
detect_extensions = []
detect_files = []

[nodejs]
format = "[$symbol$version]($style) "
symbol = "Node "
style = "#179299"

[cmd_duration]
format = "[$duration]($style)"
style = "#df8e1d"
